### ISSUE TITLE
Settings administration page

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#193]
We need a page where a user can administer ~~site-wide~~ _global_ settings. The navigation already has a "Settings" link, so we just need a corresponding controller and views. Some ideas for settings:

* Results per page (default 25)
* What information to accompany property labels on show pages: "Nothing", "Show vocabulary", "Show term" (e.g. `dcterms:title`; default "Nothing")

Any other ideas?

**Comment by patrickmj** [comment]
Seems like theme, slug, and navigation are implied by what the model has, and I'm guessing these would be part of Settings?

These might be bigger and touch on changes to the model

* Public/private sites? (people currently want to make an entire site hidden while building)
* Public API availability (might or might not be same setting as above)

**Comment by jimsafley** [comment]
Sorry, I wrote "site-wide", but meant "global". I've corrected the mistake above.

**Comment by patrickmj** [comment]
* _maybe_ same things as in O2 security settings?
* global admin email
* contact info (for things like take-down requests)
* Public API access setting

I can also imagine some places wanting to set some footer HTML that would appear across all of the individual sites' headers and footers for branding purposes. Some universities still have that in official policy.
